# Generated by Django 5.1 on 2026-08-30 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_no', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('phase', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['milestone_no'],
            },
        ),
        migrations.CreateModel(
            name='SoilReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100, unique=True)),
                ('dominant_soil_type', models.CharField(max_length=100)),
                ('susceptibility', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['district'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('material', models.CharField(choices=[('BRICKS', 'Bricks'), ('CEMENT', 'Cement'), ('SAND', 'Sand'), ('CRUSH', 'Crush'), ('STEEL', 'Steel')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_rate_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', 'district', 'material'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50, unique=True)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner_cnic_hash', models.CharField(max_length=128)),
                ('division', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('tehsil', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('project_type', models.CharField(choices=[('VACANT_PLOT', 'Vacant Plot'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('COMPLETED_HOME', 'Completed Home')], max_length=30)),
                ('plot_size_marla', models.FloatField()),
                ('covered_area_sqft', models.FloatField()),
                ('loan_approved', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loan_disbursed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('plans_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('environment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('quality_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('site_risk_flag', models.BooleanField(default=False)),
                ('overall_progress_pct', models.FloatField(default=0.0)),
                ('current_milestone_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_engineer', models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'FIELD_ENGINEER')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_ratings', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_no', models.CharField(choices=[('ONE', 'Visit 1'), ('TWO', 'Visit 2'), ('THREE', 'Visit 3')], max_length=10)),
                ('visit_date', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('progress_pct_reported', models.FloatField()),
                ('engineer_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='projects.project')),
            ],
            options={
                'ordering': ['-visit_date'],
                'unique_together': {('project', 'visit_no')},
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_no', models.IntegerField()),
                ('image_ref', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('gps_accuracy_m', models.FloatField()),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.project')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='projects.visit')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_no', models.IntegerField(choices=[(1, 'Milestone 1'), (2, 'Milestone 2'), (3, 'Milestone 3'), (4, 'Milestone 4'), (5, 'Milestone 5'), (6, 'Milestone 6'), (7, 'Milestone 7'), (8, 'Milestone 8'), (9, 'Milestone 9'), (10, 'Milestone 10'), (11, 'Milestone 11'), (12, 'Milestone 12'), (13, 'Milestone 13'), (14, 'Milestone 14'), (15, 'Milestone 15')])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_milestones', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'milestone_no'],
                'unique_together': {('project', 'milestone_no')},
            },
        ),
    ]
