# Generated by Django 5.1 on 2026-09-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cnic', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('degree_16', models.CharField(blank=True, max_length=255)),
                ('degree_18', models.CharField(blank=True, max_length=255)),
                ('division', models.CharField(max_length=100)),
                ('assigned_district', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Junior Engineer',
                'verbose_name_plural': 'Junior Engineers',
                'ordering': ['sr_no'],
            },
        ),
    ]
