# Generated by Django 4.2.20 on 2026-08-30 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_match_confidence', models.FloatField(default=0.0)),
                ('blur_score', models.FloatField(default=0.0)),
                ('is_blurred', models.BooleanField(default=False)),
                ('defects_json', models.JSONField(blank=True, default=dict)),
                ('proposed_grade', models.CharField(choices=[('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('SATISFACTORY', 'Satisfactory'), ('NOT_SATISFACTORY', 'Not Satisfactory')], default='GOOD', max_length=30)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate_of_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='projects.photo')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='projects.photo')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_no', models.IntegerField()),
                ('decision', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('OVERRIDDEN', 'Overridden'), ('REJECTED', 'Rejected')], max_length=20)),
                ('final_grade', models.CharField(choices=[('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('SATISFACTORY', 'Satisfactory'), ('NOT_SATISFACTORY', 'Not Satisfactory')], max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('rectification_text', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role__in': ['BACKEND_REVIEW_ENGINEER', 'ADMIN']}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
                'unique_together': {('project', 'milestone_no')},
            },
        ),
    ]
