# Generated by Django 5.1 on 2026-08-30 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESSCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trees_requiring_permission', models.BooleanField(default=False)),
                ('near_settlements', models.BooleanField(default=False)),
                ('near_drainage_nullah', models.BooleanField(default=False)),
                ('blocks_right_of_way', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('photo_path', models.CharField(blank=True, max_length=500)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ess_check', to='projects.visit')),
            ],
        ),
        migrations.CreateModel(
            name='HSECheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(choices=[('PPE_WORN', 'PPE Worn'), ('DUST_MASKS_USED', 'Dust Masks Used'), ('DRINKING_WATER_AVAILABLE', 'Drinking Water Available'), ('NO_CHILD_LABOUR', 'No Child Labour'), ('NO_INJURIES', 'No Injuries'), ('DEBRIS_DISPOSED_PROPERLY', 'Debris Disposed Properly')], max_length=50)),
                ('answer', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'N/A')], max_length=5)),
                ('remarks', models.TextField(blank=True)),
                ('photo_path', models.CharField(blank=True, max_length=500)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hse_checks', to='projects.visit')),
            ],
            options={
                'ordering': ['visit', 'item_key'],
                'unique_together': {('visit', 'item_key')},
            },
        ),
    ]
