# Generated by Django 4.2.20 on 2026-08-30 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_status', models.CharField(choices=[('UNDER_CONSTRUCTION', 'Under Construction'), ('PENDING_HANDOVER', 'Pending Handover'), ('HANDED_OVER', 'Handed Over')], default='UNDER_CONSTRUCTION', max_length=30)),
                ('handover_date', models.DateTimeField(blank=True, null=True)),
                ('occupant_count', models.IntegerField(blank=True, null=True)),
                ('occupant_details', models.JSONField(blank=True, default=dict)),
                ('electricity_connected', models.BooleanField(default=False)),
                ('gas_connected', models.BooleanField(default=False)),
                ('drainage_connected', models.BooleanField(default=False)),
                ('water_supply_connected', models.BooleanField(default=False)),
                ('beneficiary_signed_at', models.DateTimeField(blank=True, null=True)),
                ('engineer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_path', models.CharField(blank=True, max_length=500)),
                ('certificate_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_signatures', to=settings.AUTH_USER_MODEL)),
                ('engineer_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_signatures', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
