# Generated by Django 5.1 on 2026-08-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
