# Generated by Django 4.2.20 on 2026-08-30 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DPR', 'Daily Progress Report'), ('DISTRICT_EXCEL', 'District Excel Export'), ('HANDOVER_SUMMARY', 'Handover Summary Report')], max_length=50)),
                ('scope', models.CharField(choices=[('DISTRICT', 'District'), ('DIVISION', 'Division'), ('ALL', 'All')], default='ALL', max_length=20)),
                ('scope_value', models.CharField(blank=True, max_length=100, null=True)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
